on: [pull_request]

name: Review Buddy

jobs:
  chatgpt_comment:
    runs-on: ubuntu-latest
    name: Let ChatGPT review on your PR.
    steps:
      - name: ChatGPT Review
        uses: aw-square/review-buddy@main
        id: chatgpt
        with:
          number: ${{ github.event.pull_request.number }}
          sessionToken: ${{ secrets.CHATGPT_SESSION_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
